/*
 * Wavetek 80 defs.
 *
 */

/* Operating modes */
#define MEAS_WAVETEK80_MODE_NORMAL            0
#define MEAS_WAVETEK80_MODE_LINEAR_SWEEP      1
#define MEAS_WAVETEK80_MODE_LOGARITHMIC_SWEEP 2
#define MEAS_WAVETEK80_MODE_PLL               3

/* Sweep direction */
#define MEAS_WAVETEK80_SWEEP_UP      1
#define MEAS_WAVETEK80_SWEEP_DOWN    2
#define MEAS_WAVETEK80_SWEEP_UP_DOWN 3
#define MEAS_WAVETEK80_SWEEP_DOWN_UP 4

/* Trigger modes */
#define MEAS_WAVETEK80_TRIGGER_CONTINUOUS       1
#define MEAS_WAVETEK80_TRIGGER_EXTERNAL_TRIGGER 2
#define MEAS_WAVETEK80_TRIGGER_EXTERNAL_GATE    3
#define MEAS_WAVETEK80_TRIGGER_EXTERNAL_BURST   4
#define MEAS_WAVETEK80_TRIGGER_INTERNAL_TRIGGER 5
#define MEAS_WAVETEK80_TRIGGER_INTERNAL_BURST   6

/* Control modes */
#define MEAS_WAVETEK80_CONTROL_OFF 0
#define MEAS_WAVETEK80_CONTROL_FM  1
#define MEAS_WAVETEK80_CONTROL_AM  2
#define MEAS_WAVETEK80_CONTROL_VCO 4

/* Output waveforms */
#define MEAS_WAVETEK80_WAVEFORM_DC              0
#define MEAS_WAVETEK80_WAVEFORM_SINE            1
#define MEAS_WAVETEK80_WAVEFORM_TRIANGLE        2
#define MEAS_WAVETEK80_WAVEFORM_SQUARE          3
#define MEAS_WAVETEK80_WAVEFORM_SQUARE_POSITIVE 4
#define MEAS_WAVETEK80_WAVEFORM_SQUARE_NEGATIVE 5

/* Output modes */
#define MEAS_WAVETEK80_OUTPUT_NORMAL   0
#define MEAS_WAVETEK80_OUTPUT_DISABLED 1
